name: tiime

channels:
  - conda-forge

dependencies:
  - python=3.9
  - jupyterlab
  - jupyter_console

  ## Development tools
  - black
  - flake8
  - isort
  - pytest
  - colorlog

  ## Data engineering
  - pandas==1.4.*

  ## I/O
  - metaflow==2.*.*
  - sqlite-utils==3.*.*
  - twilio==7.*.*

  ## PIP packages
  - pip
    